// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GenAIBoilerplate.Tests.BDD.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class UserAuthenticationFeature : object, Xunit.IClassFixture<UserAuthenticationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Authentication.feature"
#line hidden
        
        public UserAuthenticationFeature(UserAuthenticationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "User Authentication", "    As a user of the GenAI platform\n    I want to authenticate securely\n    So th" +
                    "at I can access my personalized AI chatbot experience", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
    await testRunner.GivenAsync("the GenAI platform is running", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("the database is clean", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Successful user registration")]
        [Xunit.TraitAttribute("FeatureTitle", "User Authentication")]
        [Xunit.TraitAttribute("Description", "Successful user registration")]
        [Xunit.TraitAttribute("Category", "authentication")]
        [Xunit.TraitAttribute("Category", "smoke")]
        public async System.Threading.Tasks.Task SuccessfulUserRegistration()
        {
            string[] tagsOfScenario = new string[] {
                    "authentication",
                    "smoke"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successful user registration", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.GivenAsync("I am a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "FirstName",
                            "LastName"});
                table1.AddRow(new string[] {
                            "user@example.com",
                            "SecurePass123",
                            "John",
                            "Doe"});
#line 13
    await testRunner.WhenAsync("I register with valid credentials:", ((string)(null)), table1, "When ");
#line hidden
#line 16
    await testRunner.ThenAsync("I should receive a successful registration response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 17
    await testRunner.AndAsync("I should receive a JWT access token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync("I should receive a refresh token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync("my user account should be created in the database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Successful user login")]
        [Xunit.TraitAttribute("FeatureTitle", "User Authentication")]
        [Xunit.TraitAttribute("Description", "Successful user login")]
        [Xunit.TraitAttribute("Category", "authentication")]
        [Xunit.TraitAttribute("Category", "smoke")]
        public async System.Threading.Tasks.Task SuccessfulUserLogin()
        {
            string[] tagsOfScenario = new string[] {
                    "authentication",
                    "smoke"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successful user login", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "FirstName",
                            "LastName"});
                table2.AddRow(new string[] {
                            "user@example.com",
                            "SecurePass123",
                            "John",
                            "Doe"});
#line 23
    await testRunner.GivenAsync("I have an existing user account:", ((string)(null)), table2, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table3.AddRow(new string[] {
                            "user@example.com",
                            "SecurePass123"});
#line 26
    await testRunner.WhenAsync("I login with valid credentials:", ((string)(null)), table3, "When ");
#line hidden
#line 29
    await testRunner.ThenAsync("I should receive a successful login response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 30
    await testRunner.AndAsync("I should receive a JWT access token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
    await testRunner.AndAsync("I should receive a refresh token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 32
    await testRunner.AndAsync("the access token should contain valid user claims", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Failed login with invalid credentials")]
        [Xunit.TraitAttribute("FeatureTitle", "User Authentication")]
        [Xunit.TraitAttribute("Description", "Failed login with invalid credentials")]
        [Xunit.TraitAttribute("Category", "authentication")]
        [Xunit.TraitAttribute("Category", "security")]
        public async System.Threading.Tasks.Task FailedLoginWithInvalidCredentials()
        {
            string[] tagsOfScenario = new string[] {
                    "authentication",
                    "security"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Failed login with invalid credentials", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "FirstName",
                            "LastName"});
                table4.AddRow(new string[] {
                            "user@example.com",
                            "SecurePass123",
                            "John",
                            "Doe"});
#line 36
    await testRunner.GivenAsync("I have an existing user account:", ((string)(null)), table4, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table5.AddRow(new string[] {
                            "user@example.com",
                            "WrongPass123"});
#line 39
    await testRunner.WhenAsync("I login with invalid credentials:", ((string)(null)), table5, "When ");
#line hidden
#line 42
    await testRunner.ThenAsync("I should receive an authentication error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 43
    await testRunner.AndAsync("I should not receive any tokens", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 44
    await testRunner.AndAsync("the error message should indicate invalid credentials", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registration with duplicate email")]
        [Xunit.TraitAttribute("FeatureTitle", "User Authentication")]
        [Xunit.TraitAttribute("Description", "Registration with duplicate email")]
        [Xunit.TraitAttribute("Category", "authentication")]
        [Xunit.TraitAttribute("Category", "security")]
        public async System.Threading.Tasks.Task RegistrationWithDuplicateEmail()
        {
            string[] tagsOfScenario = new string[] {
                    "authentication",
                    "security"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registration with duplicate email", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "FirstName",
                            "LastName"});
                table6.AddRow(new string[] {
                            "user@example.com",
                            "SecurePass123",
                            "John",
                            "Doe"});
#line 48
    await testRunner.GivenAsync("I have an existing user account:", ((string)(null)), table6, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "FirstName",
                            "LastName"});
                table7.AddRow(new string[] {
                            "user@example.com",
                            "NewPass123",
                            "Jane",
                            "Smith"});
#line 51
    await testRunner.WhenAsync("I attempt to register with the same email:", ((string)(null)), table7, "When ");
#line hidden
#line 54
    await testRunner.ThenAsync("I should receive a validation error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 55
    await testRunner.AndAsync("the error message should indicate email already exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 56
    await testRunner.AndAsync("no new user account should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Registration with invalid data")]
        [Xunit.TraitAttribute("FeatureTitle", "User Authentication")]
        [Xunit.TraitAttribute("Description", "Registration with invalid data")]
        [Xunit.TraitAttribute("Category", "authentication")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.InlineDataAttribute("invalid-email", "SecurePass", "John", "Doe", "Invalid email", new string[0])]
        [Xunit.InlineDataAttribute("user@example.com", "weak", "John", "Doe", "Password must be", new string[0])]
        [Xunit.InlineDataAttribute("user@example.com", "SecurePass", "", "Doe", "First name is required", new string[0])]
        [Xunit.InlineDataAttribute("user@example.com", "SecurePass", "John", "", "Last name is required", new string[0])]
        public async System.Threading.Tasks.Task RegistrationWithInvalidData(string email, string password, string firstName, string lastName, string expectedError, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "authentication",
                    "validation"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email", email);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("FirstName", firstName);
            argumentsOfScenario.Add("LastName", lastName);
            argumentsOfScenario.Add("ExpectedError", expectedError);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registration with invalid data", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 59
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 60
    await testRunner.GivenAsync("I am a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "FirstName",
                            "LastName"});
                table8.AddRow(new string[] {
                            string.Format("{0}", email),
                            string.Format("{0}", password),
                            string.Format("{0}", firstName),
                            string.Format("{0}", lastName)});
#line 61
    await testRunner.WhenAsync("I register with invalid credentials:", ((string)(null)), table8, "When ");
#line hidden
#line 64
    await testRunner.ThenAsync("I should receive a validation error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 65
    await testRunner.AndAsync(string.Format("the error message should contain \"{0}\"", expectedError), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Token refresh with valid refresh token")]
        [Xunit.TraitAttribute("FeatureTitle", "User Authentication")]
        [Xunit.TraitAttribute("Description", "Token refresh with valid refresh token")]
        [Xunit.TraitAttribute("Category", "authentication")]
        [Xunit.TraitAttribute("Category", "tokens")]
        public async System.Threading.Tasks.Task TokenRefreshWithValidRefreshToken()
        {
            string[] tagsOfScenario = new string[] {
                    "authentication",
                    "tokens"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Token refresh with valid refresh token", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 75
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 76
    await testRunner.GivenAsync("I have a logged-in user with valid tokens", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 77
    await testRunner.WhenAsync("I request a token refresh using the refresh token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 78
    await testRunner.ThenAsync("I should receive a new access token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 79
    await testRunner.AndAsync("I should receive a new refresh token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 80
    await testRunner.AndAsync("the old refresh token should be invalidated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 81
    await testRunner.AndAsync("the new access token should contain valid user claims", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Token refresh with invalid refresh token")]
        [Xunit.TraitAttribute("FeatureTitle", "User Authentication")]
        [Xunit.TraitAttribute("Description", "Token refresh with invalid refresh token")]
        [Xunit.TraitAttribute("Category", "authentication")]
        [Xunit.TraitAttribute("Category", "tokens")]
        public async System.Threading.Tasks.Task TokenRefreshWithInvalidRefreshToken()
        {
            string[] tagsOfScenario = new string[] {
                    "authentication",
                    "tokens"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Token refresh with invalid refresh token", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 84
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 85
    await testRunner.GivenAsync("I have an invalid or expired refresh token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 86
    await testRunner.WhenAsync("I request a token refresh using the invalid token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 87
    await testRunner.ThenAsync("I should receive an authentication error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 88
    await testRunner.AndAsync("I should not receive any new tokens", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 89
    await testRunner.AndAsync("the error message should indicate invalid refresh token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Access protected endpoint with valid token")]
        [Xunit.TraitAttribute("FeatureTitle", "User Authentication")]
        [Xunit.TraitAttribute("Description", "Access protected endpoint with valid token")]
        [Xunit.TraitAttribute("Category", "authentication")]
        [Xunit.TraitAttribute("Category", "security")]
        public async System.Threading.Tasks.Task AccessProtectedEndpointWithValidToken()
        {
            string[] tagsOfScenario = new string[] {
                    "authentication",
                    "security"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Access protected endpoint with valid token", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 92
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 93
    await testRunner.GivenAsync("I have a logged-in user with valid tokens", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 94
    await testRunner.WhenAsync("I access a protected endpoint with the access token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 95
    await testRunner.ThenAsync("I should receive a successful response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 96
    await testRunner.AndAsync("the response should contain user-specific data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Access protected endpoint without token")]
        [Xunit.TraitAttribute("FeatureTitle", "User Authentication")]
        [Xunit.TraitAttribute("Description", "Access protected endpoint without token")]
        [Xunit.TraitAttribute("Category", "authentication")]
        [Xunit.TraitAttribute("Category", "security")]
        public async System.Threading.Tasks.Task AccessProtectedEndpointWithoutToken()
        {
            string[] tagsOfScenario = new string[] {
                    "authentication",
                    "security"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Access protected endpoint without token", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 99
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 100
    await testRunner.WhenAsync("I access a protected endpoint without any token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 101
    await testRunner.ThenAsync("I should receive an unauthorized error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 102
    await testRunner.AndAsync("the response status should be 401", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Access protected endpoint with expired token")]
        [Xunit.TraitAttribute("FeatureTitle", "User Authentication")]
        [Xunit.TraitAttribute("Description", "Access protected endpoint with expired token")]
        [Xunit.TraitAttribute("Category", "authentication")]
        [Xunit.TraitAttribute("Category", "security")]
        public async System.Threading.Tasks.Task AccessProtectedEndpointWithExpiredToken()
        {
            string[] tagsOfScenario = new string[] {
                    "authentication",
                    "security"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Access protected endpoint with expired token", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 105
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 106
    await testRunner.GivenAsync("I have an expired access token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 107
    await testRunner.WhenAsync("I access a protected endpoint with the expired token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 108
    await testRunner.ThenAsync("I should receive an unauthorized error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 109
    await testRunner.AndAsync("the response status should be 401", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 110
    await testRunner.AndAsync("the error message should indicate token has expired", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="User logout with token revocation")]
        [Xunit.TraitAttribute("FeatureTitle", "User Authentication")]
        [Xunit.TraitAttribute("Description", "User logout with token revocation")]
        [Xunit.TraitAttribute("Category", "authentication")]
        [Xunit.TraitAttribute("Category", "logout")]
        public async System.Threading.Tasks.Task UserLogoutWithTokenRevocation()
        {
            string[] tagsOfScenario = new string[] {
                    "authentication",
                    "logout"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User logout with token revocation", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 113
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 114
    await testRunner.GivenAsync("I have a logged-in user with valid tokens", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 115
    await testRunner.WhenAsync("I logout from the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 116
    await testRunner.ThenAsync("I should receive a successful logout response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 117
    await testRunner.AndAsync("my access token should be revoked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 118
    await testRunner.AndAsync("my refresh token should be revoked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get current user profile")]
        [Xunit.TraitAttribute("FeatureTitle", "User Authentication")]
        [Xunit.TraitAttribute("Description", "Get current user profile")]
        [Xunit.TraitAttribute("Category", "authentication")]
        [Xunit.TraitAttribute("Category", "profile")]
        public async System.Threading.Tasks.Task GetCurrentUserProfile()
        {
            string[] tagsOfScenario = new string[] {
                    "authentication",
                    "profile"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get current user profile", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 121
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 122
    await testRunner.GivenAsync("I have a logged-in user with valid tokens", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 123
    await testRunner.WhenAsync("I request my user profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 124
    await testRunner.ThenAsync("I should receive my profile information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table9.AddRow(new string[] {
                            "Email",
                            "user@example.com"});
                table9.AddRow(new string[] {
                            "FirstName",
                            "John"});
                table9.AddRow(new string[] {
                            "LastName",
                            "Doe"});
                table9.AddRow(new string[] {
                            "Role",
                            "User"});
#line 125
    await testRunner.AndAsync("the profile should contain:", ((string)(null)), table9, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Update user profile")]
        [Xunit.TraitAttribute("FeatureTitle", "User Authentication")]
        [Xunit.TraitAttribute("Description", "Update user profile")]
        [Xunit.TraitAttribute("Category", "authentication")]
        [Xunit.TraitAttribute("Category", "profile")]
        public async System.Threading.Tasks.Task UpdateUserProfile()
        {
            string[] tagsOfScenario = new string[] {
                    "authentication",
                    "profile"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update user profile", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 133
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 134
    await testRunner.GivenAsync("I have a logged-in user with valid tokens", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "Phone"});
                table10.AddRow(new string[] {
                            "Johnny",
                            "Doe",
                            "1234567890"});
#line 135
    await testRunner.WhenAsync("I update my profile with new information:", ((string)(null)), table10, "When ");
#line hidden
#line 138
    await testRunner.ThenAsync("I should receive a successful update response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 139
    await testRunner.AndAsync("my profile should be updated in the database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 140
    await testRunner.AndAsync("when I request my profile again, it should show the updated information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UserAuthenticationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await UserAuthenticationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
